I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter02.rpy", line 107, in script
    ila "Name’s Ilana. What’s yours?"
Exception: Sayer 'ila' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter02.rpy", line 107, in script
    ila "Name’s Ilana. What’s yours?"
  File "C:\Users\prans\Downloads\Setups\renpy-7.4.11-sdk.7z\renpy-7.4.11-sdk/renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\prans\Downloads\Setups\renpy-7.4.11-sdk.7z\renpy-7.4.11-sdk/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'ila' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
donor 1.0
Thu Jan 20 18:59:36 2022
