I'm sorry, but an uncaught exception occurred.

While running game code:
<<<<<<< HEAD
  File "game/script.rpy", line 158, in script
    jump day_2
ScriptError: could not find label 'day_2'.
=======
  File "game/script.rpy", line 104, in script
    jump tco_1
ScriptError: could not find label 'tco_1'.
>>>>>>> 59b0de2833122ba237c1516bdf61e72a4a512ab2

-- Full Traceback ------------------------------------------------------------

Full traceback:
<<<<<<< HEAD
  File "game/script.rpy", line 158, in script
    jump day_2
  File "C:\Users\sadat\Desktop\renpy-7.4.11-sdk\renpy\ast.py", line 1773, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\sadat\Desktop\renpy-7.4.11-sdk\renpy\script.py", line 917, in lookup
=======
  File "game/script.rpy", line 104, in script
    jump tco_1
  File "C:\Users\prans\Downloads\Setups\renpy-7.4.10-sdk\renpy\ast.py", line 1773, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\prans\Downloads\Setups\renpy-7.4.10-sdk\renpy\script.py", line 917, in lookup
>>>>>>> 59b0de2833122ba237c1516bdf61e72a4a512ab2
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'tco_1'.

<<<<<<< HEAD
Windows-10-10.0.19042
Ren'Py 8.0.0.22011702n
 
Wed Jan 19 16:42:04 2022
=======
Windows-10-10.0.19044
Ren'Py 8.0.0.22011701n
testing 1 1.0
Wed Jan 19 14:27:58 2022
>>>>>>> 59b0de2833122ba237c1516bdf61e72a4a512ab2
